### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by Conan-Kudo** [fuhry/piclicktrack#1]
Qt 4 (and PyQt4) is no longer developed. Please migrate to Qt 5 and [PyQt5](https://pypi.python.org/pypi/PyQt5).

**Comment by fuhry** [comment]
I know, I tried to use PyQt5 and things are moved around a lot and nobody has written a good migration guide.

**Comment by kkofler** [comment]
It's mostly just things (all the widget-related stuff) that moved from QtGui to QtWidgets.

I think `sed -i -e 's/PyQt4/PyQt5/g' -e 's/QtGui/QtWidgets/g' clicktrack/gui.py` is probably enough to make this work with PyQt5 (but it needs to be tested).

**Comment by fuhry** [comment]
Interesting, OK. I had been looking for instructions this straightforward and the migration guides I found online were not helpful at all.

Will give this a shot this evening, thanks!
